create table public.providers (
    id bigint generated by default as identity primary key,
    name text not null,
    service text not null,
    area text not null,
    phone text not null,
    approved boolean not null default false,
    created_at timestamptz not null default now()
);

create table public.service_requests (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    service text not null,
    area text not null,
    details text not null,
    created_at timestamptz not null default now()
);

alter table public.providers enable row level security;
alter table public.service_requests enable row level security;

create policy "Anyone can view approved providers"
on public.providers for select
using (approved = true);

create policy "Anyone can register as a provider"
on public.providers for insert
with check (approved = false);

create policy "Anyone can create service requests"
on public.service_requests for insert
with check (true);
